language: elixir
elixir: 1.9
notifications:
  recipients:
    - joaomdmoura@gmail.com
env:
  - MIX_ENV=test
script:
  - mix deps.get
  - mix format --check-formatted
  - mix test
  - mix coveralls.travis
